display:
  cycle: true
  inverted: false
  orientation: 90
mining:
  enabled: false
  key:
  organisation:
  secret:
ticker:
  coinname: true
  currency: bitcoin-cash,monero,mithril,litecoin,ravencoin,bitcoin,ethereum,stellar
  exchange: default
  fiatcurrency: cad
  sparklinedays: 7
  updatefrequency: 120
