display:
  cycle: true
  inverted: false
  orientation: 270
ticker:
  coinname: false
  currency: ethereum,stellar,bitcoin-cash,monero,mithril,litecoin,ravencoin,bitcoin
  exchange: default
  fiatcurrency: cad
  sparklinedays: 7
  updatefrequency: 30
